# Generated by Django 4.0.1 on 2022-02-20 23:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_rename_department_pol'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pol',
            new_name='Department',
        ),
    ]
