# Generated by Django 5.1.5 on 2025-07-11 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_pol_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='policy',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='department',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Owner of this department entry', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(help_text='Which department this policy belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='base.department')),
            ],
        ),
    ]
