# Generated by Django 5.1.5 on 2025-07-12 08:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_policy_department_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='content',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='summary',
        ),
        migrations.AddField(
            model_name='policy',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, help_text='Upload your policy document (PDF, DOCX, etc.)', upload_to='policies/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policy',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='base.department'),
        ),
    ]
